<div class="col-sm-9">
	<section id="game_info_section" class="game_info row">
		<div class="col-md-4">
			<img id="game_img" src="" alt="">
		</div>
		<div class="col-md-8">
			<h2 id="game_title">Realtime Player Data</h2>
			<a id="game_events_readme" href="" target="_blank">View README for the game events</a><br>
			<a id="game_features_readme" href="" target="_blank">View README for the processed features</a><br>
			<a id="game_link" href="" target="_blank">Play the game</a>
		</div>
	</section>
	<table id="game_files_table">
		<tr><td>Waiting for table to load...</td></tr>
	</table>
	<section id="ogd_info_section" class="pub-wrap">
		<h2>How does this work?</h2>
		<p class="small">Each month, the data generated by players in each game is exported to this site in several forms. SQL and CSV are raw files and contain only the events generated by the game. The descriptions of these events are found at the game's readme.md file at the game's repository, and linked below.</p>
		<p class="small">The processed CSV contains calculated features from each game play session and organizes them all in one row. These features are described in the game's readme.md file in the opengamedata repository, and linked below.</p>

		<p class="small"><span id="game_title_2">WAVES</span> Game <a id="game_events_readme_2" target="_blank" href="https://github.com/fielddaylab/waves/blob/master/README.md">Readme</a>
			<span id="game_title_3">WAVES</span> Feature Extractor <a id="game_features_readme_2" href='https://opengamedata.fielddaylab.wisc.edu/data/WAVES/readme.md'>Readme</a>
		</p>

		<p class="small">For simple educational data mining purposes, the processed files can be used as examples to predict behaviors such as quitting or performance on an embedded assessment.</p>
		<p class="small">Alternately, the feature extractor code may be modified to perform your own feature engineering. In this case, you will likely want to import the raw SQL files into your own server, clone the opengamedata repository and run "python main [arguments]" to generate your own processed files. If you derive any interesting features, please share them back with us!</p>
		<p class="small">We are actively looking for research collaborators. Reach out and we can discuss potential research project and funding options.</p>
	</section>
</div>